### PR TITLE
Create closestnumbertozero.cpp

### LINKED ISSUE #22: cpp version of closest number to zero
There should be a cpp version for closest number to zero problem solution

### PR DESCRIPTION
**Pull request by mrsparkle-70**
fixes #22 
Added cpp solution for closest number to zero problem of leetcode

### CODE REVIEW

**Comment by mrsparkle-70** [comment]
@durgesh2001 done

**Comment by mrsparkle-70** [comment]
@durgesh2001 can u revert back with any update ?

**Comment by mrsparkle-70** [comment]
sticks #45

**Comment by soumdatta81** [comment]
i would like to share a solution

**Pull request merged**
